name: tedcomccommands
version: "1.0-SNAPSHOT"
main: dev.nifusion.tedcomccommands.Tedcomccommands
api-version: "1.21"
commands:
  fling:
    description: Fling a player into the air.
    usage: /fling <player> <power>
    permission: fling.use
  floatyheals:
    description: Flings a splash potion of health from the player.
    usage: /floatyheals <player> <count>
    permission: floatyheals.use
  makeitrainheals:
    description: Rains lingering potions of health on the player.
    usage: /makeitrainheals <player> <count>
    permission: makeitrainheals.use
  smackdatass:
    description: Gives the player a firm, healing booty smack.
    usage: /smackdatass <player>
    permission: smackdatass.use
  feedme:
    description: Feeds the player a little munchies
    usage: /feedme <player> <power>
    permission: smackdatass.use
  queue:
    description: Manage the player's command queue
    usage: /<command> [clear]
    permission: queue.manage
    permission-message: You do not have permission to use this command.
  stream:
    description: Manage the player's stream events
    usage: /<command> <action>
    permission: stream.manage
    permission-message: You do not have permission to use this command.
permissions:
  fling.use:
    description: Allows a player to use the fling command
    default: op
  floatyheals.use:
    description: Allows a player to use the floatyheals command
    default: op
  makeitrainheals.use:
    description: Allows a player to use the makeitrainheals command
    default: op
  smackdatass.use:
    description: Allows a player to use the smackdatass command
    default: op
  feedme.use:
    description: Allows a player to use the feedme command
    default: op
